// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

  

#define CONFIG_IMG_SRC_USING_FILE 1
 
#define LV_IMG_DECLARE_FILE(var_name) extern lv_img_dsc_t var_name;
LV_IMG_DECLARE_FILE(ui_img_btt_logo_png);
LV_IMG_DECLARE_FILE(ui_img_start_btt_logo_png);
    
LV_IMG_DECLARE_FILE(ui_img_a1_series_png);   // assets\a1_series.png
LV_IMG_DECLARE_FILE(ui_img_p1_series_png);   // assets\p1_series.png
LV_IMG_DECLARE_FILE(ui_img_x1_series_png);   // assets\x1_series.png

LV_IMG_DECLARE_FILE(ui_img_guide_bg_png);
LV_IMG_DECLARE_FILE(ui_img_guide_1_png);
LV_IMG_DECLARE_FILE(ui_img_guide_2_png);
LV_IMG_DECLARE_FILE(ui_img_guide_3_png);
LV_IMG_DECLARE_FILE(ui_img_guide_4_png);
LV_IMG_DECLARE_FILE(ui_img_guide_5_png);

LV_IMG_DECLARE_FILE(ui_img_icon_model_png); 
LV_IMG_DECLARE_FILE(gif_hello);

LV_IMG_DECLARE_FILE(ui_img_extrude_png);
LV_IMG_DECLARE_FILE(ui_img_retract_png);
LV_IMG_DECLARE_FILE(ui_img_icon_knob_png);

#if 1
LV_IMG_DECLARE_FILE( ui_img_ctl_home_png);
LV_IMG_DECLARE_FILE( ui_img_ctl_ctl_png);
#else
LV_IMG_DECLARE( ui_img_ctl_home_png);
LV_IMG_DECLARE( ui_img_ctl_ctl_png);
#endif


LV_IMG_DECLARE_FILE( ui_img_ctl_print_png);
LV_IMG_DECLARE_FILE( ui_img_ctl_setting_png);
LV_IMG_DECLARE_FILE( ui_img_ctl_printers_png);

LV_IMG_DECLARE_FILE( ui_img_wifi_png);
LV_IMG_DECLARE_FILE( ui_img_nozzle_png);
LV_IMG_DECLARE_FILE( ui_img_hotbed_png);
LV_IMG_DECLARE_FILE( ui_img_temp_png);
LV_IMG_DECLARE_FILE( ui_img_little_fan_png);
LV_IMG_DECLARE_FILE( ui_img_speed_png);
LV_IMG_DECLARE_FILE( ui_img_x_dec_10_png);
LV_IMG_DECLARE_FILE( ui_img_x_inc_10_png);
LV_IMG_DECLARE_FILE( ui_img_x_dec_1_png);
LV_IMG_DECLARE_FILE( ui_img_x_inc_1_png);
LV_IMG_DECLARE_FILE( ui_img_y_dec_10_png);
LV_IMG_DECLARE_FILE( ui_img_y_inc_10_png);
LV_IMG_DECLARE_FILE( ui_img_y_dec_1_png);
LV_IMG_DECLARE_FILE( ui_img_y_inc_1_png);
LV_IMG_DECLARE_FILE( ui_img_home_png);
LV_IMG_DECLARE_FILE( ui_img_z_inc_png);
LV_IMG_DECLARE_FILE( ui_img_z_dec_png);
LV_IMG_DECLARE_FILE( ui_img_e_inc_png);
LV_IMG_DECLARE_FILE( ui_img_e_dec_png);
//LV_IMG_DECLARE_FILE( ui_img_pwd_mode_png);

LV_IMG_DECLARE_FILE( ui_img_pointer_png);
LV_IMG_DECLARE_FILE( ui_img_mqtt_disconnect_png);
LV_IMG_DECLARE_FILE( ui_img_mqtt_connect_png);
LV_IMG_DECLARE_FILE( ui_img_network_speed_png);  

LV_IMG_DECLARE_FILE( ui_img_led_on_png);
LV_IMG_DECLARE_FILE( ui_img_led_off_png);
LV_IMG_DECLARE_FILE( ui_img_pause_png);
LV_IMG_DECLARE_FILE( ui_img_resume_png);
LV_IMG_DECLARE_FILE( ui_img_stop_png);
LV_IMG_DECLARE_FILE( ui_img_menu_png);
LV_IMG_DECLARE_FILE( ui_img_close_png);
LV_IMG_DECLARE_FILE( ui_img_menu_png);

LV_IMG_DECLARE_FILE( ui_img_edit_png);
 
LV_IMG_DECLARE_FILE( ui_img_q1_png);
LV_IMG_DECLARE_FILE( ui_img_q2_png);
LV_IMG_DECLARE_FILE( ui_img_q3_png);
LV_IMG_DECLARE_FILE( ui_img_info_png);

LV_IMG_DECLARE_FILE(ui_img_guide_1_en_png);
LV_IMG_DECLARE_FILE(ui_img_guide_2_en_png);
LV_IMG_DECLARE_FILE(ui_img_guide_3_en_png);
LV_IMG_DECLARE_FILE(ui_img_guide_4_en_png);
LV_IMG_DECLARE_FILE(ui_img_guide_5_en_png);
LV_IMG_DECLARE_FILE(ui_img_guide_1_cn_png);
LV_IMG_DECLARE_FILE(ui_img_guide_2_cn_png);
LV_IMG_DECLARE_FILE(ui_img_guide_3_cn_png);
LV_IMG_DECLARE_FILE(ui_img_guide_4_cn_png);
LV_IMG_DECLARE_FILE(ui_img_guide_5_cn_png);
LV_IMG_DECLARE_FILE(ui_img_icon_power_png);
LV_IMG_DECLARE_FILE(ui_img_dot_png);   
LV_IMG_DECLARE_FILE(ui_img_bigger_png);  
LV_IMG_DECLARE_FILE(ui_img_smaller_png);  
LV_IMG_DECLARE_FILE(ui_img_unbind_png);
LV_IMG_DECLARE_FILE(ui_img_countdown_png); 
 
LV_IMG_DECLARE_FILE(ui_img_current_png);
LV_IMG_DECLARE_FILE(ui_img_ele_used_png);
LV_IMG_DECLARE_FILE(ui_img_power_png);
LV_IMG_DECLARE_FILE(ui_img_volt_png);  
LV_IMG_DECLARE_FILE(ui_img_power_is_off_png);
LV_IMG_DECLARE_FILE(ui_img_power_is_on_png);
LV_IMG_DECLARE_FILE(ui_img_power_ctl_png);
LV_IMG_DECLARE_FILE(ui_img_reset_pwr_usage_png);
LV_IMG_DECLARE_FILE(ui_img_usb_off_png);
LV_IMG_DECLARE_FILE(ui_img_usb_on_png);
LV_IMG_DECLARE_FILE(ui_img_power_ctl_big_png);


LV_IMG_DECLARE_FILE(ui_img_account_png);
LV_IMG_DECLARE_FILE(ui_img_login_failed_png);
LV_IMG_DECLARE_FILE(ui_img_region_png);
LV_IMG_DECLARE_FILE(ui_img_cloud_disable_png);
LV_IMG_DECLARE_FILE(ui_img_cloud_enable_png);

LV_IMG_DECLARE_FILE(ui_img_a1_png);
LV_IMG_DECLARE_FILE(ui_img_x1c_png);
LV_IMG_DECLARE_FILE(ui_img_a1_mini_png);
LV_IMG_DECLARE_FILE(ui_img_p1p_png);
LV_IMG_DECLARE_FILE(ui_img_p1s_png);
LV_IMG_DECLARE_FILE(ui_img_a1_ams_png);
LV_IMG_DECLARE_FILE(ui_img_a1_mini_ams_png);
LV_IMG_DECLARE_FILE(ui_img_p1p_ams_png);
LV_IMG_DECLARE_FILE(ui_img_p1s_ams_png);
LV_IMG_DECLARE_FILE(ui_img_x1c_ams_png);
  
LV_IMG_DECLARE(ui_img_pwd_mode_png);
LV_IMG_DECLARE_FILE(ui_img_humidity_png);
LV_IMG_DECLARE_FILE(ui_img_temperature_png);
LV_IMG_DECLARE_FILE(ui_img_extruder_png);
LV_IMG_DECLARE_FILE(ui_img_x1c_drying_png);

LV_IMG_DECLARE_FILE(ui_img_humidity_0_png);
LV_IMG_DECLARE_FILE(ui_img_humidity_1_png);
LV_IMG_DECLARE_FILE(ui_img_humidity_2_png);
LV_IMG_DECLARE_FILE(ui_img_humidity_3_png);
LV_IMG_DECLARE_FILE(ui_img_humidity_4_png); 

LV_FONT_DECLARE( opensansb12); 
LV_FONT_DECLARE( opensansb16);
LV_FONT_DECLARE( opensansb20);
LV_FONT_DECLARE( opensansb24); 
 
#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
